Práctica numpy

Lista tradicional vs arreglos numpy

In [ ]:
lista = [2,4.3,'Hola']
lista[2]

In [ ]:
matriz = [[1,2,3],
          [4,5,6],
          [7,8,9]]
print(matriz[1][1])

In [ ]:
import numpy as np
numeros = [2,56,7,8]
#a = np.array([2,56,7,8])
a = np.array(numeros)
#print(type(a))
print(a)

In [ ]:
#secuencia = np.arange(3,15,2)
secuencia = np.linspace(2, 10, 4)
secuencia

In [ ]:
#ceros = np.zeros((3,5))
#ceros
#unos = np.ones(5)
#unos
custom = np.full((2,5), 5)
custom2 = custom ** 2
custom2

In [ ]:
base = np.linspace(2,6,4)
#base
print(np.full_like(base,np.pi))

In [ ]:
#azar = np.random.rand(5,3)
azar = np.random.randn(5,3)
print(azar)


In [53]:
#a = np.full((4,4), 16)
#b = np.reshape(a, [2,4,2])
azar2 = np.random.randn(4,4)
azar2


array([[-0.47818278,  0.0440484 , -0.53872928,  0.85424626],
       [-0.45215686,  1.19078856, -1.6874638 , -0.76088828],
       [-0.21829116, -1.51904685, -1.04079757,  0.33219379],
       [ 0.43878155,  0.14986078, -1.79317247, -0.06561657]])

In [57]:
b = np.reshape(azar2, (2,4,2))
b
#print(b.dtype)

array([[[-0.47818278,  0.0440484 ],
        [-0.53872928,  0.85424626],
        [-0.45215686,  1.19078856],
        [-1.6874638 , -0.76088828]],

       [[-0.21829116, -1.51904685],
        [-1.04079757,  0.33219379],
        [ 0.43878155,  0.14986078],
        [-1.79317247, -0.06561657]]])

In [62]:
matriz = np.arange(1,10).reshape(3,3)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
#matriz[1,1]
#matriz[0,:]
#matriz[:, 1]
matriz[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [76]:
a = np.arange(20).reshape(2,10)
mascara = a % 2 == 0
print(a[mascara])
mascara

[ 0  2  4  6  8 10 12 14 16 18]


array([[ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])